# Generated by Django 4.1 on 2022-09-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='borrow',
            field=models.CharField(blank=True, choices=[('w', 'waiting'), ('d', 'denied'), ('e', 'approved')], default='w', max_length=1),
        ),
    ]
